### ISSUE TITLE
svelte-confetti doesn't appear to be written in CJS

### ISSUE THREAD

**Issue by amr3k** [Mitcheljager/svelte-confetti#1]
I just upgraded to the latest version `"svelte-confetti": "^1.2.1"` and found this warning:

`
svelte-confetti doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
`

So like my computer said, I'm contacting you here to fix this :)

**Comment by Mitcheljager** [comment]
@amr3k This 23b746426fa1b880bd62b6fbbe4d98783276c979 should have fixed the issue in version 1.2.2. Please let me know if it hasn't!
