### ISSUE TITLE
Create Sub Package or Upgrade For Svelte5

### ISSUE THREAD

**Issue by sansjack** [Mitcheljager/svelte-confetti#11]
Just wondering if we could get a svelte5 update or sub package for this?
When using svelte5 i am getting the following dependency error:
```
npm error While resolving: monitro@0.0.1
npm error Found: svelte@5.0.0-next.192
npm error node_modules/svelte
npm error   dev svelte@"^5.0.0-next.191" from the root project
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^4.0.0 || ^5.0.0" from svelte-confetti@2.0.1
npm error node_modules/svelte-confetti
npm error   svelte-confetti@"*" from the root project
```

**Comment by Mitcheljager** [comment]
Version 1.x is reserved for Svelte 4, and version 2.x is for Svelte 5 going forward. There's still some annoying dependencies, but I think I've managed to suppress them. Using version 2.1.1 and above should work. I've also updated the docs to reflect the changes.
Please let me know if it all works as expected!

**Comment by dyc3** [comment]
It would be great to mention that in the readme and the docs website.

**Comment by Mitcheljager** [comment]
It is mentioned in the docs
![image](https://github.com/user-attachments/assets/18ba78d2-dfb9-44a7-85ed-f60c62f88192)

I'll update the readme too

**Comment by sansjack** [comment]
This is much appreciated, Amazing work btw 😃

**Comment by sansjack** [comment]
> Version 1.x is reserved for Svelte 4, and version 2.x is for Svelte 5 going forward. There's still some annoying dependencies, but I think I've managed to suppress them. Using version 2.1.1 and above should work. I've also updated the docs to reflect the changes. Please let me know if it all works as expected!

seems like im getting this error when doing `npm install svelte-confetti@^2.1.1 --save-dev`
```
npm error Found: svelte@5.0.0-next.192
npm error node_modules/svelte
npm error   dev svelte@"^5.0.0-next.192" from the root project
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^5.0.0" from svelte-confetti@2.1.1
npm error node_modules/svelte-confetti
npm error   dev svelte-confetti@"^2.1.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by dyc3** [comment]
FYI this is what I'm seeing on https://mitcheljager.github.io/svelte-confetti/

![image](https://github.com/user-attachments/assets/30e96d1f-d0cb-4a15-930c-debf85abec4f)

**Comment by Mitcheljager** [comment]
@dyc3 Ah sorry, try again

**Comment by dyc3** [comment]
Yup, I see it now. Thanks!
