### ISSUE TITLE
Wrong example in the documentation 

### ISSUE THREAD

**Issue by jussetain** [Mitcheljager/svelte-confetti#16]
# Issue 

In the "everywhere" example under the Spread section, the (displayed) x and y props are incorrect.

![image](https://github.com/user-attachments/assets/a5199d7c-872d-4d50-b85a-15d8e1114f0c)

# Solution

The GitHub Pages have already been built, so I couldn't create a pull request. The correct values should be: `<Confetti x={[-0.5, 0.5]} y={[0.5, -0.5]} />`.

**Comment by Mitcheljager** [comment]
Thanks!
