### ISSUE TITLE
Context interfering with other Canvas

### ISSUE THREAD

**Issue by steddyman** [Mitcheljager/svelte-confetti#17]
I have an existing component on my site, that binds a canvas to a canvas var, then inside onMount, I do the following:

```javascript
	onMount(() => {
		ctx = canvas.getContext('2d');
	});
```

However, since adding <Canvas /> to the parent page (which is working), I get the following runtime error inside the above onMount function:

  GameBoard.svelte:94 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getContext')
    at GameBoard.svelte:94:16
    at Array.map (<anonymous>)

**Comment by steddyman** [comment]
Sorry, issue appears to be elsewhere in the game logic.  Please ignore.

**Comment by steddyman** [comment]
Closing

**Comment by Mitcheljager** [comment]
No problem! Feel free to re-open if something comes up
