### ISSUE TITLE
Confetti rain lagging

### ISSUE THREAD

**Issue by CustomEntity** [Mitcheljager/svelte-confetti#7]
Hello, when I take back the confetti rain from the documentation my whole page starts to lag whereas on the documentation site no problem, would you know where this could be coming from? Example [here](https://valodle.eu/classic). The today's answer is "Neon".

**Comment by Mitcheljager** [comment]
I'm having a hard time reproducing it, as it heavily depends on your own device and set up. A large amount of elements are created for the confetti, depending on the `amount` prop. By themselves this shouldn't be a huge deal, but if you have things like MutationObservers running, they might have to work a little harder when they elements are created. 

I will close this issue for now, but feel free to re-open if you can provide an isolated environment where this happens.
