### ISSUE TITLE
Breaking version published as minor 1.3.0

### ISSUE THREAD

**Issue by durasj** [Mitcheljager/svelte-confetti#8]
Hi there,

Thank you for this nicely documented library!

It's nice if npm dependencies can follow the semver. By default, deps are installed with `^`, and so minor versions are included.

Version [1.3.0](https://www.npmjs.com/package/svelte-confetti/v/1.3.0) was published as a minor update despite bringing a breaking change - dependency on Svelte 4. Following the semver, it should've been `2.0.0`.

There is not much one can do at this point since it would require quite a bit of work, but I'm just letting you know nicely, as I see this was done on multiple of your npm packages and it complicates things for people using the packages downstream.

Thanks again

**Comment by Mitcheljager** [comment]
Ah you're right, I should have, apologies!

**Comment by Cainuriel** [comment]
I don't know if it has anything to do with this thread but I have a dependency error when installing it.

```
ERR! Could not resolve dependency:
npm ERR! peer svelte@"^4.0.0" from svelte-confetti@1.3.0
```
my package:
```
	"devDependencies": {
		"@playwright/test": "^1.30.0",
		"@sveltejs/adapter-auto": "^1.0.2",
		"@sveltejs/adapter-netlify": "^1.0.0-next.88",
		"@sveltejs/kit": "^1.3.10",
		"@typescript-eslint/eslint-plugin": "^5.50.0",
		"@typescript-eslint/parser": "^5.50.0",
		"eslint": "^8.33.0",
		"eslint-config-prettier": "^8.6.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.3",
		"prettier-plugin-svelte": "^2.9.0",
		"prisma": "^4.14.1",
		"rome": "^11.0.0",
		"svelte": "^3.55.1",
		"svelte-check": "^3.0.3",
		"tslib": "^2.5.0",
		"typescript": "^4.9.5",
		"vite": "^4.1.1",
		"vitest": "^0.25.8"
	},
	"type": "module",
	"dependencies": {
		"@lucia-auth/adapter-prisma": "^2.0.0",
		"@picocss/pico": "^1.5.7",
		"@prisma/client": "^4.9.0",
		"lucia-auth": "^1.7.0",
		"svelte-select": "^5.7.0",
		"svelte-toasts": "^1.1.2",
		"xrpl": "^2.11.0"
	}
```

**Comment by Mitcheljager** [comment]
Version 1.3.0 uses Svelte 4. If you want to keep using Svelte 3 you will need to use any version prior to 1.3.0

**Comment by Cainuriel** [comment]
Oh yes, it's the other way round. The latest version is in your library not in my project.

I have chosen version ```v1.2.2``` and it works perfectly.
Thanks for taking the time to answer me.
Best regards.
